spring:
  datasource:
    url: jdbc:h2:mem:stationdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect

server:
  port: 8082
booking:
  service:
    url: http://localhost:8083
